E_Shop/Cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    path()
]

E_Shop/E_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Accounts.urls")),
    path('', include("Products.urls")),
    path('', include("DependApp.urls")),





    path('', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Shop/Products/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    path("base/", base, name="base"),


    # path("", home, name="home"),
    path("", home.as_view(), name="home"),


    #path("Products_Details/<slug:slug>/", Products_Details, name="Products_Details"),
    path("Products_Details/<slug:slug>/", Products_Details.as_view(), name="Products_Details"),
    #path("Products_Details/<int:pk>/", Products_Details.as_view, name="Products_Details"),


    # path("products_show/<int:m_id>/", products_show, name="products_show"),
    # path("products_show/<int:m_id>/<int:c_id>/", products_show, name="products_show"),
    # path("products_show/<int:m_id>/<int:c_id>/<int:s_id>/", products_show, name="products_show"),

    path("products_show/<int:m_id>/", products_show.as_view(), name="products_show"),
    path("products_show/<int:m_id>/<int:c_id>/", products_show.as_view(), name="products_show"),
    path("products_show/<int:m_id>/<int:c_id>/<int:s_id>/", products_show.as_view(), name="products_show"),



    # path('filter/',filter_data,name="filter-data"),
    path('filter/',filter_data.as_view(),name="filter-data"),
    



    #path("404/", Error404, name="Error404"),
    path("404/", Error404.as_view(), name="Error404"),
]

E_Shop/Products/models.py
from django.db import models
# ------CK Editors--------------------
from ckeditor.fields import RichTextField


#------For Slug Fild-----------------------------
from django.utils.text import slugify
from django.db.models.signals import pre_save


# Create your models here.
# ------------------------All Category Start-------------------------------------------------------------------------------
class Main_Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    main_category = models.ForeignKey(Main_Category, on_delete=models.CASCADE, related_name="Category")
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name + "__" + self.main_category.name


class Sub_Category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="Sub_Category")
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name + "__" + self.category.name + "__" + self.category.main_category.name


# ------------------------All Category End-------------------------------------------------------------------------------

# ------------------------All Products Start-----------------------------------------------------------------------------

class Section(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    Total_quantity      = models.IntegerField(default=1)
    Availability        = models.IntegerField(default=1)
    Image               = models.CharField(max_length=200)
    Product_name        = models.CharField(max_length=100)
    Price               = models.IntegerField(default=0)
    Discount_Price      = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    Discount            = models.IntegerField(default=0)
    Product_information = RichTextField(null=True, blank=True)
    Tags                = models.CharField(max_length=100, null=True, blank=True)
    Description         = RichTextField(null=True, blank=True)

    slug                = models.SlugField(default='', max_length=500, null=True, blank=True)
    main_category       = models.ForeignKey(Main_Category, on_delete=models.CASCADE)
    category            = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category        = models.ForeignKey(Sub_Category, on_delete=models.CASCADE, null=True, blank=True)
    section             = models.ForeignKey(Section, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.Product_name
    
    def save(self, *args, **kwargs):
        self.Discount_Price = self.Price - (self.Price * self.Discount / 100)
        super(Products, self).save(*args, **kwargs)
# --------------------------------For Add Slug Fild in Model Start------------------------------------------
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("Products_Details", kwargs={'slug': self.slug})

    class Meta:
        db_table = "app_Products"


def create_slug(instance, new_slug=None):
    slug = slugify(instance.Product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Products.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Products)
# --------------------------------For Add Slug Fild in Model End------------------------------------------

class Product_Images(models.Model):
    product   = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="Product_Images")
    Image_url = models.CharField(max_length=200, null=True, blank=True)


class Additional_Information(models.Model):
    product       = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="Additional_Information")
    Specification = models.CharField(max_length=100, null=True, blank=True)
    detail        = models.CharField(max_length=100, null=True, blank=True)

# ------------------------All Products End-------------------------------------------------------------------------------

E_Shop/Products/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
import os
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template.loader import render_to_string
from .models import *


# For Paginator--------------------------------------
from django.core.paginator import Paginator

# Redirect Function base view to Class base view-------------------------
from django.urls import reverse_lazy


#------------------------------------------------------------------------
from django.views.generic.base import TemplateView, RedirectView
# Display View-----------------------------------------------------------
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Editing View-----------------------------------------------------------
from django.views.generic import CreateView, UpdateView, DeleteView

# Aggregate  Function-----------------------------------------------------
# from django.db.models import Max, Min, Avg, Sum
from django.db.models import Avg, Max, Min

# Create your views here.

def base(request):
    return render(request, "index.html")

#------------------------------------------Home Page Render------------------------------------
# Function

# def home(request):
    # main_cats = Main_Category.objects.all()
    # product = Products.objects.filter(section__name="Top Deals Of The Day")
    # product_sell = Products.objects.filter(section__name="Top Selling Products")
    # product_Recommended = Products.objects.filter(section__name="Recommended For You")

    # shop = Main_Category.objects.all()[:5]


    # context = {
    #     "main_cats": main_cats,
    #     "product": product,
    #     "product_sell": product_sell,
    #     "product_Recommended": product_Recommended,
    #     "shop": shop,
    # }
    # return render(request, "home.html", context)


### Class Base View
class home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        # Pass data by template_context.py ---------------------------------------------------------
        # data['main_cats'] = Main_Category.objects.all()
        # data['product'] = Products.objects.filter(section__name="Top Deals Of The Day")
        # print("-----------------------------")
        # print(data['product'])
        # print("-----------------------------")
        # data['product_sell'] = Products.objects.filter(section__name="Top Selling Products")
        # data['product_Recommended'] = Products.objects.filter(section__name="Recommended For You")

        # data['shop'] = Main_Category.objects.all()[:5]

        return data


#--------------------------------------------------Product Detail-------------------------------------
# Function View

# def Products_Details(request, slug):
#     main_cats = Main_Category.objects.all()

#     product = Products.objects.filter(slug=slug)
#     if product.exists():
#         product = Products.objects.filter(slug=slug)
#     else:
#         return redirect("Error404")

#     data = {
#         "product": product,
#         "main_cats": main_cats,
#     }
#     return render(request, "Products/product-details.html", data)

# Class View
class Products_Details(DetailView):
    model = Products
    template_name = "Products/product-details.html"
    context_object_name = 'product'

    # slug_field = 'slug'
    # slug_url_kwarg = 'get_absolute_url'

    # def get_object(self, queryset=None):
    #     try:
    #         return super().get_object(queryset=queryset)
    #     except Http404:
    #         return redirect("Error404")

    def dispatch(self, request, *args, **kwargs):
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return redirect("Error404")

        
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # if not self.object:
        #     raise Http404("Product does not exist")
        data = self.get_context_data(object=self.object)
        # data['main_cats'] = Main_Category.objects.all()
        # data['shop'] = Main_Category.objects.all()[:5]
        return self.render_to_response(data)

    # def get_context_data(self, *args, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     data['main_cats'] = Main_Category.objects.all()
    #     return data
    

#--------------------------------------------Error 404 Page---------------------------------------------------

# def Error404(request):
#     return render(request, "404.html")


class Error404(TemplateView):
    template_name = "404.html"
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # data['main_cats'] = Main_Category.objects.all()
        # data['cats'] =Category.objects.all()
        # data['shop'] = Main_Category.objects.all()[:5]
        return data
    

#-----------------------------------------------All Product Show by Catagory-------------------------------------
# Function View

# def products_show(request, *args, **kwargs):
#     main_cats = Main_Category.objects.all()
#     cats =Category.objects.all()
#     minMaxPrice = Products.objects.aggregate(Max("Price"), Min("Price"))
#     products =Products.objects.all()
#     brand = ""

#     m_id = kwargs.get('m_id')
#     c_id = kwargs.get('c_id')
#     s_id = kwargs.get('s_id')
#     # print("-------------")
#     # print(m_id,c_id,s_id)
#     # print("-------------")

#     if (m_id !=None) and (c_id== None) and (s_id== None):
#         products = Products.objects.filter(main_category__id = m_id)
#         #brand = Sub_Category.objects.filter(category__id = c_id)
#         # print("----------------------")
#         # print(products)
#         # print("----------------------")
#         # q = Category.objects.filter(main_category__id=m_id)
        
#     elif (m_id!=None) and (c_id!=None) and (s_id==None):
#         products = Products.objects.filter(Q(main_category__id = m_id) & Q(category__id = c_id))
#         brand = Sub_Category.objects.filter(category__id = c_id)
#         # print("----------------------")
#         # print("id-2:",products)
#         # print("----------------------")
#     elif m_id and c_id and s_id:
#         products = Products.objects.filter(Q(main_category__id = m_id) & Q(category__id = c_id) & Q(sub_category__id = s_id))
#         brand = Sub_Category.objects.filter(category__id = c_id)
#         # print("----------------------")
#         # print("id-3:",products)
#         # print("----------------------")
#     else:
#         products =Products.objects.all()

#     # Pagination-------------------------------------------------
#     paginator = Paginator(products, 8)  # Show 25 contacts per page.
#     a = paginator.count
#     # print("Total Products =", a)
#     page_number = request.GET.get('page')
#     # print("Page Number =",page_number)
#     page_obj = paginator.get_page(page_number)
#     # print("Next =", page_obj)
#     nums = "a" * page_obj.paginator.num_pages
#     #-----------------------------------------------------------
    

#     data = {
#         "main_cats": main_cats,
#         "cats": cats,
#         # "products": products,
#         "minMaxPrice": minMaxPrice,
#         "brand": brand,

#         "page_number": page_number,
#         "page_obj": page_obj,
#         "nums": nums,
#     }
#     return render(request, "Products/shop.html", data)



## Class View
class products_show(ListView):
    template_name = "Products/shop.html"
    model = Products
    paginate_by = 12
    # context_object_name = 'products'
    
    def get_context_data(self, *args, **kwargs):
        data= super().get_context_data(**kwargs)
        data['minMaxPrice'] = Products.objects.aggregate(Max("Price"), Min("Price"))
        m_id = self.kwargs.get('m_id')
        c_id = self.kwargs.get('c_id')
        s_id = self.kwargs.get('s_id')
        # print("-------------")
        # print(m_id, c_id, s_id)
        # print("-------------")

        if (m_id !=None) and (c_id== None) and (s_id== None):
            data['brand']=""
        elif (m_id!=None) and (c_id!=None) and (s_id==None):
            data['brand'] = Sub_Category.objects.filter(category__id=c_id)
            # print("----------- S_id--------------")
            # print(data['brand'])
            # print("------------------------------")
        elif m_id and c_id and s_id:
            data['brand'] = Sub_Category.objects.filter(category__id=c_id)
            # print("----------- S_id--------------")
            # print(data['brand'])
            # print("------------------------------")
    
        return data
    
    def get_queryset(self):
        queryset = super().get_queryset()
        m_id = self.kwargs.get('m_id')
        c_id = self.kwargs.get('c_id')
        s_id = self.kwargs.get('s_id')

        if m_id:
            queryset = queryset.filter(main_category__id = m_id)
        if m_id and c_id:
            queryset = queryset.filter(Q(main_category__id = m_id) & Q(category__id = c_id))
        if m_id and c_id and s_id:
            queryset = queryset.filter(Q(main_category__id = m_id) & Q(category__id = c_id) & Q(sub_category__id = s_id))


        return queryset
    
#-----------------------------------------------Products Filter--------------------------------------------------------        



# def filter_data(request):
#     categories = request.GET.getlist('category[]')
#     sub_catagory = Sub_Category.objects.filter(category__id__in=categories)

#     brands = request.GET.getlist('brand[]')
#     if brands:    
#         Cat = Category.objects.filter(Sub_Category__id__in=brands)
#         sub_catagory = Sub_Category.objects.filter(category__id__in=Cat)


#     minPrice = request.GET['minPrice']
#     maxPrice = request.GET['maxPrice'] 

E_Shop/Products/templates/Products/shop/brands.html
{%  load static %}
{% load Products_Discount_Price %}
{% for brand in brand %}
<div class="single-widget-category">
    <input type="checkbox" data-filter="brand" id="brand-{{brand.id}}" value="{{brand.id}}" class="filter-checkbox">
    <label for="brand-{{brand.id}}">{{brand.name}}-{{brand.id}} <span>( {{brand.products_set.all.count}} )</span></label>
</div>
{% endfor %}

E_Shop/Products/templates/Products/shop/filter.html
{%  load static%}

{% load Products_Discount_Price %}
{% block css %}
<style>
    input[type=range]{
    -webkit-appearance: none;
    width:100%;
    }
    input[type=range]::-webkit-slider-runnable-track {
    width: 1000px;
    height: 5px;
    background: #FCBE00;
    border: none;
    border-radius: 3px;
    }
    input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none;
    border: none;
    height: 16px;
    width: 16px;
    border-radius: 50%;
    background: goldenrod;
    margin-top: -5px;
    }
    input[type=range]:focus {
    outline: none;
    }
    input[type=range]:focus::-webkit-slider-runnable-track {
    background: #FCBE00;
    }
</style>
<style>
    .wrapper {
      overflow: hidden; /* This is to contain the floated elements within the wrapper */
    }
    .left {
      float: left;
    }
    .right {
      float: right;
    }
  </style>
{% endblock css %}
<!---------------------------------------------- Catagory Filter Start --------------------------------------->
<div class="col-xl-3 col-lg-4">
    <div class="product-widget mb-30">
        <h5 class="pt-title">Product categories</h5>
        <div class="widget-category-list mt-20">
            {% for cat in cats %}
            <div class="single-widget-category">
                <input type="checkbox" data-filter="category" id="catagory-{{cat.id}}" value="{{cat.id}}" class="filter-checkbox">
                <label for="catagory-{{cat.id}}">{{cat.name}} <span>( {{cat.products_set.all.count}} )</span> </label>
            </div>
            {% endfor %}
        </div>
    </div>
<!---------------------------------------------- Catagory Filter End --------------------------------------->

<!---------------------------------------------- Brand Filter Start ------------------------------------->     
    <div class="product-widget mb-30">
        <h5 class="pt-title">Choose Brand</h5>
        <div class="widget-category-list mt-20">
            <div id="brands">
                {% include "Products\shop\brands.html" %}
            </div>
        </div>
    </div>
<!---------------------------------------------- Brand Filter End -------------------------------------> 
                                    
<!---------------------------------------------- Price Filter Start --------------------------------------->
<div class="product-widget mb-30">
    <h5 class="pt-title">Filter By Price</h5>
    <div class="price__slider mt-30">
        <li class="list-group-item" style="height: 70px;">
            <input type="range" class="multi-range success" id="rangeInput" style="color:red;" min="{{minMaxPrice.Price__min}}" max="{{minMaxPrice.Price__max}}" oninput="maxPrice.value=this.value" width="400px;" value="{{minMaxPrice.Price__min}}"/>
            <div class="left">{{minMaxPrice.Price__min}}</div>
            <div class="right">{{minMaxPrice.Price__max}}</div>
        </li>
        <li class="list-group-item">
            Given Your Price: <input type="number" value="{{minMaxPrice.Price__max}}" max="{{minMaxPrice.Price__max}}" min="{{minMaxPrice.Price__min}}" class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" />
            <button type="submit" id="priceFilterBtn" class="btn btn-outline-warning btn-sm mt-4 ml-2">Filter</button>
        </li>
    </div>
 </div>
<!---------------------------------------------- Price Filter End --------------------------------------->



    <!-- <div class="product-widget mb-30">
        <h5 class="pt-title">Special Offers</h5>
        <div class="product__sm mt-20">
            <ul>
                <li class="product__sm-item d-flex align-items-center">
                    <div class="product__sm-thumb mr-20">
                        <a href="product-details.html">
                            <img src="{% static 'assets/img/product/sm-1.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="product__sm-content">
                        <h5 class="product__sm-title">
                            <a href="product-details.html">Classic Leather Backpack Daypack 2022</a>
                        </h5>
                        <div class="product__sm-price">
                            <span class="price">$300.00</span>
                        </div>
                    </div>
                </li>
                <li class="product__sm-item d-flex align-items-center">
                    <div class="product__sm-thumb mr-20">
                        <a href="product-details.html">
                            <img src="{% static 'assets/img/product/sm-2.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="product__sm-content">
                        <h5 class="product__sm-title">
                            <a href="product-details.html">Samsung Galaxy A12, 32GB, Black - (Locked)</a>
                        </h5>
                        <div class="product__sm-price">
                            <span class="price">$150.00</span>
                        </div>
                    </div>
                </li>
                <li class="product__sm-item d-flex align-items-center">
                    <div class="product__sm-thumb mr-20">
                        <a href="product-details.html">
                            <img src="{% static 'assets/img/product/sm-3.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="product__sm-content">
                        <h5 class="product__sm-title">
                            <a href="#">Coffee Maker AH240a Full Function</a>
                        </h5>
                        <div class="product__sm-price">
                            <span class="price">$300.00</span>
                        </div>
                    </div>
                </li>
                <li class="product__sm-item d-flex align-items-center">
                    <div class="product__sm-thumb mr-20">
                        <a href="product-details.html">
                            <img src="{% static 'assets/img/product/sm-4.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="product__sm-content">
                        <h5 class="product__sm-title">
                            <a href="product-details.html">Imported Wooden Felt Cushion Chair</a>
                        </h5>
                        <div class="product__sm-price">
                            <span class="price">$120.00</span>
                        </div>
                    </div>
                </li>
                <li class="product__sm-item d-flex align-items-center">
                    <div class="product__sm-thumb mr-20">
                        <a href="product-details.html">
                            <img src="{% static 'assets/img/product/sm-5.jpg' %}" alt="">
                        </a>
                    </div>
                    <div class="product__sm-content">
                        <h5 class="product__sm-title">
                            <a href="product-details.html">Sunhouse Decorative Lights - Imported</a>
                        </h5>
                        <div class="product__sm-price">
                            <span class="price">$110.00</span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div> -->
</div>

E_Shop/Products/templates/Products/shop/pagination.html
{%  load static%}

<div class="tp-pagination text-center">
    <div class="row">
        <div class="col-xl-12">
            <div class="basic-pagination pt-30 pb-30">
                <nav>
                    {% if page_obj.has_other_pages %}
                    <ul>

                        {% if page_obj.has_previous %}
                            <li>
                                <a href="?page=1" class="">First</a>
                            </li>
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="disable"></li>
                        {% endif %}


                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li>
                                    <a class="active">{{i}}</a>
                                </li>
                            {% else %}
                                <li class="">
                                    <a class="" href="?page={{i}}">{{i}}</a>
                                </li>
                            {% endif %}
                        {% endfor %}


                        {% if page_obj.has_next %}
                            <li class="">
                                <a class="" href="?page={{ page_obj.next_page_number }}">
                                <i class="fal fa-angle-double-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                            </li>
                        {% else %}
                            <li class=" disable"></li>
                        {% endif %}
                        
                    </ul>
                    {% endif %}
                 </nav>
             </div>
        </div>
    </div>
</div>